#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww/launch_dashboard"
CFG="$HOME/.config/eww/dashboard/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
		   profile \
		   system \
		   clock \
		   uptime \
		   calendar \
           volCtrl \
		   github \
		   chatgpt \
		   gscholar \
		   youtube \
		   apps \
		   gmail \
           arch \
		   logout \
           lock \
		   reboot \
		   poweroff \
		   folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
                   profile \
                   system \
                   clock \
                   uptime \
                   calendar \
                   volCtrl \
                   github \
                   chatgpt \
                   gscholar \
                   youtube \
                   apps \
                   gmail \
                   arch \
                   logout \
                   lock \
                   reboot \
                   poweroff \
                   folders
	rm "$FILE"
fi
