#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww/launch_popup_"
CFG="$HOME/.config/eww/popup/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon --config ~/.config/eww/popup
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open wifiMenu
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else

	${EWW} --config "$CFG" close wifiMenu wifiPass
	rm "$FILE"
fi
